_wandb:
    value:
        cli_version: 0.21.1
        e:
            y64mi46i3863jtblvpvjn6lubmo3f09f:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "291689721856"
                        used: "261779152896"
                email: tsanda.alyona@gmail.com
                executable: D:\work\multilingual-sentence-embeddings\.venv\Scripts\python.exe
                git:
                    commit: 7911c06dd02060f7c9a4bfdf3dc12a59f526ee9a
                    remote: https://github.com/bbofrel/multilingual-sentence-embeddings
                host: LAPTOP-KDAGU4QB
                memory:
                    total: "8415133696"
                os: Windows-11-10.0.26100-SP0
                program: D:\work\multilingual-sentence-embeddings\main.py
                python: CPython 3.13.7
                root: D:\work\multilingual-sentence-embeddings
                startedAt: "2025-08-19T12:15:12.561421Z"
                writerId: y64mi46i3863jtblvpvjn6lubmo3f09f
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "3":
                - 16
            "4": 3.13.7
            "5": 0.21.1
            "6": 4.55.2
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
batch_size:
    value: 2
epochs:
    value: 10
lr:
    value: 2e-05
model:
    value: paraphrase-xlm-r-multilingual-v1
